apiVersion: v1
kind: Service
metadata:
  name: sitio-service
spec:
  type: NodePort
  selector:
    app: sitio-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
